apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-db
    type: database
spec:
  selector:
    app: postgres-db
    type: database
  ports:
  - port: 5432
    targetPort: db-port
  type: ClusterIP 